# Generated by Django 5.2.4 on 2025-07-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='employee',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='present',
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default=False, max_length=10),
            preserve_default=False,
        ),
    ]
